name: PHP Insights

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  insights:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: php-insights, composer
          coverage: none

      - name: Instalar dependências
        run: composer install --no-interaction --prefer-dist

      - name: Rodar PHP Insights
        run:  vendor/bin/phpinsights analyse --no-interaction --min-quality=85 --min-complexity=80 --min-architecture=80 --min-style=80
